version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
       - .:/usr/src/app
       - /usr/src/app/node_modules
    command: sh -c "npx prisma migrate deploy && npm run dev"
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      PORT: 3000
      DATABASE_URL: postgresql://postgres:mypassword@host.docker.internal:5433/gemini-vision?schema=public
    networks:
      - my_network

  postgres:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: gemini-vision
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
